export const manufacturers = [
  "Abarth",
  "Acura",
  "Alfa Romeo",
  "Alpina",
  "Apollo",
  "Ariel",
  "Ascari",
  "Aston Martin",
  "Audi",
  "Baojun",
  "Bentley",
  "BMW",
  "Borgward",
  "Bugatti",
  "Buick",
  "BYD",
  "Cadillac",
  "Caterham",
  "Chery",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Daewoo",
  "Daihatsu",
  "DeLorean",
  "Denza",
  "Dodge",
  "DS Automobiles",
  "Ferrari",
  "Fiat",
  "Fisker",
  "Force Motors",
  "Ford",
  "Genesis",
  "GMC",
  "Hennessey",
  "Hindustan Motors",
  "Holden",
  "Honda",
  "Hummer",
  "Hyundai",
  "Infiniti",
  "Isuzu",
  "Jaguar",
  "Jeep",
  "Kia",
  "Koenigsegg",
  "Lamborghini",
  "Lancia",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Lucid",
  "Mahindra",
  "Maruti Suzuki",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MG",
  "MINI",
  "Mitsubishi",
  "Nio",
  "Nissan",
  "Pagani",
  "Peugeot",
  "Polestar",
  "Porsche",
  "Proton",
  "Ram",
  "Rivian",
  "Rolls-Royce",
  "Rover",
  "Saab",
  "SEAT",
  "Skoda",
  "Smart",
  "Subaru",
  "Tata",
  "Tesla",
  "Toyota",
  "TVS Motors",
  "TVR",
  "Vauxhall",
  "VinFast",
  "Volkswagen",
  "Volvo",
  "Wiesmann",
  "Zenvo"
];

  
  export const yearsOfProduction = [
    { title: "Year", value: "" },
    { title: "2015", value: "2015" },
    { title: "2016", value: "2016" },
    { title: "2017", value: "2017" },
    { title: "2018", value: "2018" },
    { title: "2019", value: "2019" },
    { title: "2020", value: "2020" },
    { title: "2021", value: "2021" },
    { title: "2022", value: "2022" },
    { title: "2023", value: "2023" },
  ];
  
  export const fuels = [
    {
      title: "Fuel",
      value: "",
    },
    {
      title: "Gas",
      value: "Gas",
    },
    {
      title: "Electricity",
      value: "Electricity",
    },
  ];
  
  export const footerLinks = [
    {
      title: "About",
      links: [
        { title: "How it works", url: "/" },
        { title: "Featured", url: "/" },
        { title: "Partnership", url: "/" },
        { title: "Bussiness Relation", url: "/" },
      ],
    },
    {
      title: "Company",
      links: [
        { title: "Events", url: "/" },
        { title: "Blog", url: "/" },
        { title: "Podcast", url: "/" },
        { title: "Invite a friend", url: "/" },
      ],
    },
    {
      title: "Socials",
      links: [
        { title: "Discord", url: "/" },
        { title: "Instagram", url: "/" },
        { title: "Twitter", url: "/" },
        { title: "Facebook", url: "/" },
      ],
    },
  ];